import type { Metadata } from 'next';

export const metadata: Metadata = {
  description: 'Generated by me',
  title: 'Home'
};

const App = (): JSX.Element => <main>main page</main>;

export default App;
